services:
  dockreach:
    image: ${DESKTOP_PLUGIN_IMAGE}
    volumes:
      # Mount SSH configuration from the host (user's machine)
      - ~/.ssh:/root/.ssh:ro
      # Plugin data
      - "dockreach:/root/docker-extension/"

volumes:
  dockreach: